import "./App.css";
import Header from "./components/Header/Header";
import { Menu } from "./assets/svg/svg";

function App() {
  return (
    <div className="App">
      <Header />

      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <Menu />
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
      <p>balaji</p>
    </div>
  );
}

export default App;
